interface events {
    use chain.{chain-key, evm-address, evm-event-log, cosmos-address, cosmos-event};
    use core.{timestamp};
    type event-id = list<u8>; // 20-byte unique hash


    variant trigger-data {
        evm-contract-event(trigger-data-evm-contract-event),
        cosmos-contract-event(trigger-data-cosmos-contract-event),
        block-interval(trigger-data-block-interval),
        cron(trigger-data-cron),
        atproto-event(trigger-data-atproto-event),
        raw(list<u8>)
    }

    record trigger-data-evm-contract-event {
        chain: chain-key,
        log: evm-event-log,
    }

    record trigger-data-cosmos-contract-event {
        contract-address: cosmos-address,
        chain: chain-key,
        event: cosmos-event,
        event-index: u64,
        block-height: u64
    }

    record trigger-data-block-interval {
        chain: chain-key,
        block-height: u64
    }

    record trigger-data-cron {
        trigger-time: timestamp
    }

    record trigger-data-atproto-event {
        sequence: s64,
        timestamp: s64,
        repo: string,
        collection: string,
        rkey: string,
        action: string,
        cid: option<string>,
        record-data: option<string>,
        rev: option<string>,
        op-index: option<u32>
    }
}
