[default]
log_level = ["info", "warpdrive=debug"]

[warpdrive-tests]
wavs_concurrency = true
middleware_concurrency = true
grouping = false
evm_middleware_type = "poa"   # "eigenlayer" or "poa"
p2p = "kademlia"              # "mdns" (local) or "kademlia" (remote)
mode = "all_eth"
