[package]
name = "cw-warpdrive-mock-service-handler"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cw-warpdrive-mock-api = { workspace = true }
warpdrive-types = { workspace = true }
cosmwasm-std = { workspace = true }
anyhow = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
cosmwasm-schema = { workspace = true }
const-hex = { workspace = true }
alloy-sol-macro = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true }
