[package]
name = "cosmos-query"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
layer-climb = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["sync", "io-util", "rt", "time"] }
example-helpers = { workspace = true }
example-types = { workspace = true }

[lib]
crate-type = ["rlib", "cdylib"]

[package.metadata.component]
package = "warpdrive-tests:cosmos-query"
