[package]
name = "simple-aggregator"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
wit-bindgen = { workspace = true }
alloy-primitives = { workspace = true }
serde = { workspace = true }
warpdrive-wasi-utils = { workspace = true }
tokio = { workspace = true, features = ["sync", "io-util", "macros", "rt", "time"] }
layer-climb-address = { workspace = true }
stellar-strkey = { workspace = true }
warpdrive-types = { workspace = true }
wasip2 = { workspace = true }
example-helpers = { workspace = true }
example-types = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "warpdrive-tests:simple-aggregator"
