// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package host represents the imported interface "host".
package host

import (
	warpdrivetypes "github.com/Lay3rLabs/wavs-wasi/go/wavs/worker/layer-types"
	"go.bytecodealliance.org/cm"
)

// EvmChainConfig represents the type alias "host#evm-chain-config".
//
// See [warpdrivetypes.EvmChainConfig] for more information.
type EvmChainConfig = warpdrivetypes.EvmChainConfig

// CosmosChainConfig represents the type alias "host#cosmos-chain-config".
//
// See [warpdrivetypes.CosmosChainConfig] for more information.
type CosmosChainConfig = warpdrivetypes.CosmosChainConfig

// LogLevel represents the type alias "host#log-level".
//
// See [warpdrivetypes.LogLevel] for more information.
type LogLevel = warpdrivetypes.LogLevel

// GetEvmChainConfig represents the imported function "get-evm-chain-config".
//
//	get-evm-chain-config: func(chain-name: string) -> option<evm-chain-config>
//
//go:nosplit
func GetEvmChainConfig(chainName string) (result cm.Option[EvmChainConfig]) {
	chainName0, chainName1 := cm.LowerString(chainName)
	wasmimport_GetEvmChainConfig((*uint8)(chainName0), (uint32)(chainName1), &result)
	return
}

// GetCosmosChainConfig represents the imported function "get-cosmos-chain-config".
//
//	get-cosmos-chain-config: func(chain-name: string) -> option<cosmos-chain-config>
//
//go:nosplit
func GetCosmosChainConfig(chainName string) (result cm.Option[CosmosChainConfig]) {
	chainName0, chainName1 := cm.LowerString(chainName)
	wasmimport_GetCosmosChainConfig((*uint8)(chainName0), (uint32)(chainName1), &result)
	return
}

// ConfigVar represents the imported function "config-var".
//
//	config-var: func(key: string) -> option<string>
//
//go:nosplit
func ConfigVar(key string) (result cm.Option[string]) {
	key0, key1 := cm.LowerString(key)
	wasmimport_ConfigVar((*uint8)(key0), (uint32)(key1), &result)
	return
}

// Log represents the imported function "log".
//
//	log: func(level: log-level, message: string)
//
//go:nosplit
func Log(level LogLevel, message string) {
	level0 := (uint32)(level)
	message0, message1 := cm.LowerString(message)
	wasmimport_Log((uint32)(level0), (*uint8)(message0), (uint32)(message1))
	return
}
