// Code generated by wit-bindgen-go. DO NOT EDIT.

package host

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wavs:operator@0.4.0-beta.4".

//go:wasmimport host get-evm-chain-config
//go:noescape
func wasmimport_GetEvmChainConfig(chainName0 *uint8, chainName1 uint32, result *cm.Option[EvmChainConfig])

//go:wasmimport host get-cosmos-chain-config
//go:noescape
func wasmimport_GetCosmosChainConfig(chainName0 *uint8, chainName1 uint32, result *cm.Option[CosmosChainConfig])

//go:wasmimport host config-var
//go:noescape
func wasmimport_ConfigVar(key0 *uint8, key1 uint32, result *cm.Option[string])

//go:wasmimport host log
//go:noescape
func wasmimport_Log(level0 uint32, message0 *uint8, message1 uint32)
