[package]
name = "permissions"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
warpdrive-wasi-utils = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
example-helpers = { workspace = true }
example-types = { workspace = true }
tokio = { workspace = true, features = ["sync", "io-util", "macros", "rt", "time"] }

[lib]
crate-type = ["rlib", "cdylib"]

[package.metadata.component]
package = "warpdrive-tests:permissions"
