[package]
name = "cw-warpdrive-trigger-simple"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cw-warpdrive-mock-api = { workspace = true }
cw-warpdrive-trigger-api = { workspace = true }
# The workspace `warpdrive-types` has features, we need to disable them, overriding with `worksace = true` doesn't work
warpdrive-types = { workspace = true }
layer-climb-address = { workspace = true }
cosmwasm-std = { workspace = true }
anyhow = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
cosmwasm-schema = { workspace = true }
const-hex = { workspace = true }
