[package]
name = "warpdrive-stellar-mock-submit"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { version = "25", features = ["alloc"] }
alloy-sol-types = { version = "1", default-features = false }
alloy-primitives = { version = "1", default-features = false }

[dev-dependencies]
soroban-sdk = { version = "25", features = ["testutils"] }

[profile.release]
overflow-checks = true
