[metadata]
author = "Lay3r Labs Team"
description = "WarpDrive WASI Aggregator"
license = "MIT"
homepage = "https://www.wavs.xyz/"
repository = "https://github.com/warp-driver/warpdrive"

[overrides]
"wavs:types" = { path = "../types/wit" }
"wasi:tls" = { path = "../wasi-tls/wit" }
"wavs:operator" = { path = "../operator/wit" }
