[metadata]
author = "Lay3r Labs Team"
description = "WarpDrive WASI Aggregator"
license = "MIT"
homepage = "https://www.wavs.xyz/"
repository = "https://github.com/Lay3rLabs/WAVS"

[overrides]
"warpdrive:types" = { path = "../types/wit" }
"wasi:tls" = { path = "../wasi-tls/wit" }
"warpdrive:operator" = { path = "../operator/wit" }
