// Code generated by wit-bindgen-go. DO NOT EDIT.

package warpdrivetypes

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// BlockIntervalSourceShape is used for storage in variant or result types.
type BlockIntervalSourceShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(BlockIntervalSource{})]byte
}

// TriggerDataCosmosContractEventShape is used for storage in variant or result types.
type TriggerDataCosmosContractEventShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(TriggerDataCosmosContractEvent{})]byte
}
