[package]
name = "stellar-query"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
serde_json = { workspace = true }
anyhow = { workspace = true }
example-helpers = { workspace = true }
example-types = { workspace = true }
tokio = { workspace = true, features = ["sync", "io-util", "macros", "rt", "time"] }
soroban-rs = { git = "https://github.com/warp-driver/soroban-helpers", rev = "4aa7168a7321eee3e406937f214da0a42f4c9190" }

[lib]
crate-type = ["rlib", "cdylib"]

[package.metadata.component]
package = "warpdrive-tests:stellar-query"
