// Code generated by wit-bindgen-go. DO NOT EDIT.

package warpdrivetriggerworld

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// OptionWasmResponseShape is used for storage in variant or result types.
type OptionWasmResponseShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Option[WasmResponse]{})]byte
}
