// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package layertriggerworld represents the world "wavs:operator/layer-trigger-world@0.4.0-beta.4".
package warpdrivetriggerworld

import (
	warpdrivetypes "github.com/Lay3rLabs/wavs-wasi/go/wavs/worker/layer-types"
)

// TriggerAction represents the type alias "wavs:operator/layer-trigger-world@0.4.0-beta.4#trigger-action".
//
// See [warpdrivetypes.TriggerAction] for more information.
type TriggerAction = warpdrivetypes.TriggerAction

// WasmResponse represents the type alias "wavs:operator/layer-trigger-world@0.4.0-beta.4#wasm-response".
//
// See [warpdrivetypes.WasmResponse] for more information.
type WasmResponse = warpdrivetypes.WasmResponse
