// Code generated by wit-bindgen-go. DO NOT EDIT.

package warpdrivetriggerworld

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wavs:operator@0.4.0-beta.4".

//go:wasmexport run
//export run
func wasmexport_Run(triggerAction *TriggerAction) (result *cm.Result[OptionWasmResponseShape, cm.Option[WasmResponse], string]) {
	triggerAction_ := *triggerAction
	result_ := Exports.Run(triggerAction_)
	result = &result_
	return
}
