[package]
name = "chain-trigger-lookup"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
warpdrive-wasi-utils = { workspace = true }
wstd = { workspace = true }
example-helpers = { workspace = true }
anyhow = { workspace = true }
layer-climb = { workspace = true }
alloy-network = { workspace = true }
alloy-provider = { version = "=1.8.3", default-features = false }
alloy-primitives = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "warpdrive-tests:chain-trigger-lookup"
