[package]
name = "example-helpers"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
warpdrive-wasi-utils = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-contract = { workspace = true }
alloy-sol-macro = { workspace = true }
alloy-sol-types = { workspace = true }
layer-climb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
cosmwasm-std = { workspace = true }
wit-bindgen = { workspace = true }
cw-warpdrive-trigger-api = {workspace = true}
cw-warpdrive-mock-api = {workspace = true}
wasip2 = {workspace = true}
base64 = { workspace = true }
stellar-xdr = { workspace = true }
warpdrive-client = { workspace = true }

[lib]
crate-type = ["rlib", "cdylib"]
