# This can run on every commit in a PR to do some quicker tests
on: [pull_request]

name: Basic Checks

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short
  CARGO_TERM_COLOR: always
  WAVS_SUBMISSION_MNEMONIC: "test test test test test test test test test test test junk"
  WAVS_AGGREGATOR_EVM_CREDENTIAL: "test test test test test test test test test test test junk"
  # WAVS_CLI_EVM_CREDENTIAL: "test test test test test test test test test test test junk"
  # WAVS_COSMOS_SUBMISSION_MNEMONIC: "reward index time stem expire cheap worth fence coil option treat ensure install entry zone mule benefit success remain rebuild inherit eyebrow cluster sheriff"
  # WAVS_CLI_COSMOS_MNEMONIC: "reward index time stem expire cheap worth fence coil option treat ensure install entry zone mule benefit success remain rebuild inherit eyebrow cluster sheriff"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      # - name: Check compilations
      #   run: cargo check --all-targets --all-features

  test:
    name: Basic Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Test WarpDrive CLI
        run: cargo test -p warpdrive-cli --lib -- --skip test_set_component_source_registry

      - name: Test WarpDrive Types
        run: cargo test -p warpdrive-types --lib

      - name: Test WarpDrive Engine
        run: cargo test -p warpdrive-engine --lib

      - name: Test WarpDrive (no anvil, cosmos)
        run: cargo test -p warpdrive --lib -- --skip evm_stream

